# .goreleaser.yml
project_name: caddy-trap
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - chmod -R +w $GOPATH/pkg/mod/github.com/caddyserver/caddy@v1.0.1
    - patch $GOPATH/pkg/mod/github.com/caddyserver/caddy@v1.0.1/caddyhttp/httpserver/plugin.go < directive.patch
builds:
  - binary: caddy
archives:
  - wrap_in_directory: true
