name: release

on:
  push:
    tags:
      - v2.*.*
    branches-ignore:
      - '**'

jobs:
  make-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: bash ./build.sh
      - name: Archive caddy-trap_linux_amd64
        run: |
          mkdir caddy-trap_linux_amd64
          mv caddy caddy-trap_linux_amd64/
          tar -zcvf ./caddy-trap_linux_amd64.tar.gz ./caddy-trap_linux_amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: caddy-trap_linux_amd64.tar.gz
